### ISSUE TITLE
RaiseLower only Lowers windows in per-desktop mode in certain conditions

### ISSUE THREAD

**Issue by NsCDE** [fvwmorg/fvwm3#86] opened 2020-05-22 16:24 UTC
Branch: master

If I have terminal on monitor Virtual-0, desk 0, and start "someapp" on monitor Virtual-1, desk 2, and then move it with mouse to Virtual-0, it will change desk to desk 0. I can use RaiseLower builtin function to lower it if it covers app which has been initially on Virtual-0, but raise part doesn't function: it is like window moved from Virtual-1 to Virtual-0 is on the "top" layer, with exception that I can lower native window (but not raise over newcomer window again too).

This doesn't manifests if same desk is on both monitors while moving windows.

EDIT: Additionally, in FvwmIdent, info about desk of the window moved between monitors/desks is not changed, monitor is.

**Comment by ThomasAdam** [comment] 2020-05-23 13:26
Hi @NsCDE,

Thanks for this.  I presume the window you were moving between desk not updating correctly was due to `StartsOnDesk` style?  That's certainly how I was able to reproduce this.  Please take a look at the `ta/gh-86` branch which should address this problem.  I've also fixed a bug in this which was causing `FvwmPager` not to update correctly.

As to your RaiseLower problem, I'll take a look now...

**Comment by ThomasAdam** [comment] 2020-05-24 22:08
Hi @NsCDE,

I suspect the `RaiseLower` problem has been fixed because the desk wasn't switched correctly between desks.  That said, I have made a tiny correction to the window checking for different layers, so I'm hoping that you'll find both your reported issues fixed on `ta/gh-86`.

Let me know how you get on.

**Comment by NsCDE** [comment] 2020-05-27 21:44
Hi Thomas,

Sorry for the delay, I had lot of work this days.

Just to confirm: I have tested, both RaiseLower and FvwmIdent are not behaving fine. You can close this issue I think.

**Closed** 2020-05-27 21:59 UTC
Labels: bug
