### ISSUE TITLE
the F8-menu is not shown for tigervnc-viewer

### ISSUE THREAD

**Issue by harridu** [fvwmorg/fvwm3#519] opened 2021-06-09 13:08 UTC
## Upfront Information

* Fvwm3 version
```
fvwm3 1.0.3 (released)
with support for:  ReadLine, XPM, PNG, Shape, XShm, SM, Bidi text, XRandR, XRender, XCursor, XFT, NLS
```

* Linux Distro
Debian Sid

Using tigervnc-viewer the F8 Menu ("context menu") doesn't work. The mouse pointer is changed, but the popup appears anywhere on the window, Sometimes its not shown at all. I would suspect its off screen in this case. And if I move the mouse close to the popup, then it moves away. 

No such problem for fvwm2.

## Enabling logging
```
[1623243451.028658]  log opened (because of SIGUSR2)
[1623243614.572414] setup_window_placement: Expanding screen from 'null' -> ''
[1623243626.476876] ewmh_ComputeAndSetWorkArea: monitor 'DP-0': {l: 0, r: 0, t: 0, b: 0} {x: 0, y: 0, w: 3440, h: 1440}
[1623243638.065040] ewmh_ComputeAndSetWorkArea: monitor 'DP-0': {l: 0, r: 0, t: 0, b: 0} {x: 0, y: 0, w: 3440, h: 1440}
[1623243640.590581] ewmh_ComputeAndSetWorkArea: monitor 'DP-0': {l: 0, r: 0, t: 0, b: 0} {x: 0, y: 0, w: 3440, h: 1440}
[1623243640.590620] EWMH_GetWorkAreaIntersection: mon: DP-0 {ax: 0, ay: 0, aw: 3440, ah: 1440
[1623243640.590630] EWMH_GetWorkAreaIntersection: mon: DP-0 {x: 0, y: 0, w: 3440, h: 1440
[1623243640.590638] EWMH_GetWorkAreaIntersection: mon: DP-0 finalising: {x: 0, y: 0, w: 3440, h: 1440}
```
I just ran vncviewer, pressed F8 and tried to move the mouse pointer close to the popup.

**Comment by ThomasAdam** [comment] 2021-06-09 13:25
Hey @harridu 

Weird.  Works for me.  I'm also using fvwm3-1.0.3:


https://user-images.githubusercontent.com/101281/121363131-8f03c680-c92e-11eb-804e-054814981ca8.mp4

**Comment by harridu** [comment] 2021-06-09 15:08
Amazing.

Maybe you can reproduce this using a lorge virtual (or physical) screen? I've got 3440x1440 real and in vnc.

**Comment by ThomasAdam** [comment] 2021-06-09 15:10
That's not likely.  Unless you can get me access to a VNC server at that resolution?

**Comment by harridu** [comment] 2021-06-09 15:11
Just a sec. I am trying a small screen on my side.

**Comment by harridu** [comment] 2021-06-09 15:33
Using a standard resolution (1920x1200, 24bit) for the VNC session the context menu seems to work reliable. Using a higher resolution (e.g. 2047x1200, 24bit) it works sometimes, but usually it doesn't. If it works, then it might be broken if I reconnect to the same VNC session.

I don't have a smaller monitor, but maybe you could try a vnc session with "-geometry 2048x1200 -depth 24" on your side, even if it doesn't fit on the physical screen?

**Comment by ThomasAdam** [comment] 2021-06-09 15:49
Sure.  I tried `3440x1440` as the resolution.  Works for me:

https://user-images.githubusercontent.com/101281/121387460-9765fc80-c942-11eb-98cd-72ff9042e2e1.mp4

**Comment by ThomasAdam** [comment] 2021-06-09 15:55
@harridu 

Can you add your fvwm config here, so I can check it?

**Comment by harridu** [comment] 2021-06-09 16:04
I had moved my regular .fvwm2rc out of the way. AFAICT I am using /usr/share/fvwm3/default-config/config.

**Comment by ThomasAdam** [comment] 2021-06-09 16:06
OK.  Still works fine for me.

**Comment by ThomasAdam** [comment] 2021-06-09 16:15
@harridu 

Can you also record what you're seeing?

**Comment by harridu** [comment] 2021-06-09 16:16
Which tool would you suggest to record the screen session?

I tright another vncviewer (xtightvncviewer). That showed something unexpected: The context menu showed up with its own window decorations. No problem in this case (of course).

**Comment by harridu** [comment] 2021-06-09 16:31
I have uploaded a video. But there is not very much to see. You just see how the mouse pointer is changed when I press F8.
https://user-images.githubusercontent.com/832164/121393603-cc794b80-c950-11eb-9c12-5e8928694b7a.mp4

**Comment by harridu** [comment] 2021-06-10 11:09
I could not reproduce this problem using a dual-head display in the office (2*1920x1200), connected to the same vnc session as yesterday (still using /usr/share/fvwm3/default-config/config).

**Comment by ThomasAdam** [comment] 2021-06-10 12:54
Historically, VNC has never played nicely with fvwm, due to how VNC works.  So I'm not sure what to suggest here, other than I'm unlikely to be able to fix this.

Have you tried another VNC client/server other than tightvnc to see if you get a similar issue?

**Comment by harridu** [comment] 2021-06-11 06:20
Its tigervnc. Yes, I tried tightvnc as well, see above. For tightvnc the F8 popup was shown with its own window decorations, but it was stable, AFAICT.

**Comment by ThomasAdam** [comment] 2021-06-11 10:31
OK.  At this point, unless there's something else which comes to light which allows me to reproduce it, I don't think this is necessarily fvwm's fault.

I'm going to close this bug for now, but if you get any more information, do please reopen it.

**Closed by ThomasAdam** 2021-06-11 10:31 UTC
Labels: skip:changelog, type:bug

**Comment by harridu** [comment] 2023-11-25 12:43
I am back to fvwm2 due to this problem.

**Comment by harridu** [comment] 2024-07-10 05:35
@ThomasAdam , this problem is still bugging me. Sometimes the F8 menu works as expected, sometimes it doesn't show up or runs away, as shown in the video. Creating a third window seems to toggle between "works" and "doesn't work" pretty reliably. The "Identify" from fvwm3's window context menu is very helpful here.

I wasn't able to reproduce it with other programs but tigervnc-viewer and xtightvncviewer, yet. xtightvncviewer only in full screen mode. When not in full screen mode, xtightvncviewer shows the F8 menu with window decorations.

**Comment by harridu** [comment] 2024-11-11 07:11
@ThomasAdam , I tried the current version on the main branch: Most of the time the popup is shown now (as it seems), but sometimes I still have to press F8 twice.

**Comment by harridu** [comment] 2024-11-13 11:09
Now its broken again, still using the snapshot created for #1105. Takes all the fun out of it.
