### ISSUE TITLE
Multiscreen support issue

### ISSUE THREAD

**Issue by hudmont** [fvwmorg/fvwm3#41] opened 2020-04-07 16:09 UTC
On branch ta-gh22, FVWM sometimes moves the windows to other virtual desktops instead of just going to the desktop. 

At the same time, it also messes with the cursor's functions, and the user is unable to enter input or click on a window to set focus. It resembles the behaviour of FVWM when "IgnoreModifiers L2" is not set. Of course, I set that. Alt-Tab window switching solves the focus issue.

Attached a sceenshot. On this screenshot, the focused window decoration should be orange, and unfocused window decoration should be grey.

![screenshot](https://user-images.githubusercontent.com/52786743/78692295-2e6f9880-78e9-11ea-9e29-e9b05e059836.jpg)

Attached a log as well. I can add the FvwmCommand-sxhkd config as well as my xkb layout+xmodmap, but this issue persisted even when I used Fvwm's own keybinding system.

[debug.log](https://github.com/fvwmorg/fvwm3/files/4445732/debug.log)

**Comment by ThomasAdam** [comment] 2020-04-07 16:17
Hi,

This is related to #22.

Can you send me a FVWM config which reproduces this issue?  I can see you're using `DesktopConfiguration global` and not `per-monitor` -- having just tried this myself, I can't reproduce the behaviour you're seeing.

I did push a few new changes to `ta/gh-22` last night, I presume you're running that?  HEAD commit is:  646c3da00b862e9cbf1525fb098921c9b8bbe6a4

**Comment by hudmont** [comment] 2020-04-07 16:36
I wasn't running the very latest version. I tried it  just now. GotoDeskAndPage doesn't work at all with this version. MoveToDesk works fine.
The debug output says:
monitor_by_name: couldn't find monitor: (0)

Fvwm config:
[config.txt](https://github.com/fvwmorg/fvwm3/files/4445876/config.txt)

Sxhkd config: 
[sxhkd.txt](https://github.com/fvwmorg/fvwm3/files/4445892/sxhkd.txt)

Keyboard layout (NOTE: I removed Num_Lock from mod2 , with xmodmap )
[layout.txt](https://github.com/fvwmorg/fvwm3/files/4445894/layout.txt)

**Comment by ThomasAdam** [comment] 2020-04-07 20:45
Hi,

Thanks.  The reason you see:  `monitor_by_name: couldn't find monitor: (0)` is because of how I'm tokenising the parameters to commands such as `GotoPage` and `GotoDeskAndPage`; I will tone this down, but it's unrelated to your problem.

On `ta/gh-22`, I've now fixed the parsing of `GotoDeskAndPage`.

Please try.

**Closed** 2020-04-07 20:46 UTC
Labels: bug, duplicate
