### ISSUE TITLE
Pager problems in gh-28

### ISSUE THREAD

**Issue by MasterP-theGu** [fvwmorg/fvwm3#56] opened 2020-05-02 22:47 UTC
This is all tested with the default config.

Clicking with Mousebutton 1 changes the colour of the active page, but it doesn't change the actual page. 
Clicking the Desk-number works as usual and changes desk.
One click with the Mouse button 2 and the pager turns empty or nothing happens at all (depending on ???).
Dragging a mini-icon inside the pager moves the mini-icon from one page to another, but not in reality.
Window-Menu Send-to Page works and is correctly indicated in the pager.
Mouse button 3 inside the pager does all sorts of funny things, mini-icons jump around, pager becomes empty, ...

**Comment by ThomasAdam** [comment] 2020-05-02 22:55
Duplicate of #44

**Closed** 2020-05-02 22:56 UTC
