### ISSUE TITLE
FvwmPager not taking into account global screen dimensions when configured with DeskTopScale

### ISSUE THREAD

**Issue by NsCDE** [fvwmorg/fvwm3#223] opened 2020-09-12 11:57 UTC
Hi,

Testing continues ...

DesktopConfiguration: (implicit global)

FvwmPager in [this](https://github.com/NsCDE/NsCDE/blob/fvwm3_support/NsCDE/config/NsCDE-Pager-GlobalPager.conf) configuration scales wrongly on primary, but correctly on secondary display. It is not called as transient but permanent pager with mouse action on root window menu. Restart of FVWM doesn't have impact on change.

Visualisation: Screenshot1.png is primary display Virtual-0, Screenshot2.png is secondary display. Same function called from menu with same configuration (above) but on another screen.

Sub-test:
If I append directive "*GlobalPager: Monitor $$[pointer.screen]" in configuration, dimensions of the pager are correct when called with pointer on primary screen and no windows from secondary screen are shown. If called with pointer on secondary screen, only applications from that screen are shown, but window geometry extends across both monitors, which is not the case if it is called from a primary monitor.
![Screenshot2](https://user-images.githubusercontent.com/48650374/92995006-c6f4ef00-f4ff-11ea-9070-e22b7c5cea35.png)
![Screenshot1](https://user-images.githubusercontent.com/48650374/92995007-c8261c00-f4ff-11ea-9c8e-7df83ebe7b9d.png)

**Comment by ThomasAdam** [comment] 2020-09-12 11:58
@somiaj - one for you. Any thoughts?

**Comment by NsCDE** [comment] 2020-09-12 12:04
To correct myself: in sub-test when FvwmPager is called on secondary display, in extended geometry on Screenshot2.png windows from the primary desktop ARE shown, but I cannot find a way to reproduce this glitch currently. Most of the time is like on screenshot 3 - see below.
![Screenshot3](https://user-images.githubusercontent.com/48650374/92995131-d9bbf380-f500-11ea-948d-e8f8f7f3fe9a.png)

**Comment by ThomasAdam** [comment] 2020-09-12 22:42
Hi @NsCDE,

Please can you take a look at `ta/gh-223` branch?  I am not sure I'm fully reproducing this problem correctly, but perhaps the commit I've added on that branch helps?

**Comment by NsCDE** [comment] 2020-09-13 06:35
Hi @ThomasAdam 

This is for global desktop configuration ...

With this change, FvwmPager is of the right size (after Restart when monitor is added) on both monitors and shows applications on right places for workspace 1 (desk 0). If I add

`*GlobalPager: Monitor $$[pointer.screen]`

... at the end of configuration, it rightly shows only windows from the current pointer screen monitor, but geometry of the whole pager (aspect ratio) is still wide like for two monitors.

P. S.
Additionally, I have discovered another bug when window is opened on other then first (0) desk on another monitor, but in FvwmPager it appears like it is on desk 0, not desk 1, 2 or 3. Changing to that desk really takes window there as if it was moved. This looks like per-monitor behaviour leaks into global DesktopConfiguration in FvwmPager. I will open new issue for this if you agree.

**Comment by ThomasAdam** [comment] 2020-09-13 07:24
Hi @NsCDE 

OK... Do you still get this problem if you hardcore the name of one monitor?

`*FvwmPager: Monitor foo` Vs `*FvwmPager: Monitor $$[monitor.pointer]`

As for your other observation, please feel free to open an issue!

**Comment by NsCDE** [comment] 2020-09-13 14:38
Hi @ThomasAdam 

Problem with hardwiring RandR monitor name as I have tried now is issue topic by itself.

I have Virtual-0 and Virtual-1 in test environment. If I use $$[pointer.screen] or $$[monitor.pointer] I get at least pager for separate screens, no matter how aspect ratio of pager is that of the both monitors, **but** with explicit name in Monitor option behaviour is currently like "Monitor" option is not even used - with Virtual-0 or Virtual-1 I get joined deks/pages from both monitors that is.

**Comment by ThomasAdam** [comment] 2020-09-15 14:55
Hi @NsCDE,

Yeah OK.   I see what you mean.  I have this:

```
DesktopSize 2x1

DestroyModuleConfig GlobalPager: *
*GlobalPager: DesktopScale 12
*GlobalPager: Columns 2 
```

With this config, on both `fvwm2` and `fvwm3`, I get a pager which appears to be large enough to fill two monitors, but the last part of the window is "dead".  I can't do anything with it.  This is clearly a bug.

If you remove the `Columns` and `Rows` config options from your pager config, how do things look then?

**Comment by NsCDE** [comment] 2020-09-15 16:50
Hi @ThomasAdam 

I'm happy to help with RandR debugging, but I must admit I'm not using two monitors often with fvwm2, so the news that there is a bug with FvwmPager even on fvwm2 is news to me too.

This about part of the pager window being dead ... I don't know how to reproduce this. I didn't had this situation.

On what branch to test this? Currently I'm on master because I have tested FvwmButtons fix last. In this branch, FvwmPager is of one monitor size on primary and two monitors size on secondary screen, no matter if I remove or put back Columns and Rows options.

**Comment by ThomasAdam** [comment] 2020-09-15 16:57
Hi @NsCDE ,

Please use the ta/gh-223 branch for this issue.

Don't worry about fvwm2, it was more an observation on my part that I've not necessarily broken this with my work on RandR.

Hmm, I'm clearly seeing a breakage in using Columns and/or Rows. I must be missing something.

**Comment by NsCDE** [comment] 2020-09-15 20:10
Hi

Explicit RandR names of the monitors are now taken into account. However, either with explicit names or with $$[monitor.pointer], FvwmPager size is of the joined monitor 1 and 2 geometry (on both monitors). Windows on left or right monitor are properly shown[1] according to "Monitor" configuration option or it's absence.

[1] That is, while other strange behaviours are not triggered.

**Comment by NsCDE** [comment] 2020-09-15 20:28
Additional info:
I was tired, and didn't noticed that without "Monitor" option only left/primary monitor windows are shown in FvwmPager.

**Comment by ThomasAdam** [comment] 2020-09-16 13:52
Hi @NsCDE,

OK -- please have another look at `ta/gh-223` -- I've rebased this on master, so you will probably have to:

```
git fetch && git checkout ta/gh-233 && git reset --hard @{u}
```

**Comment by NsCDE** [comment] 2020-09-16 16:49
Hi @ThomasAdam 

It seems like windows are still appearing on wrong places.

On RootWinShot.20200916.182554.png My pointer was on desk 2 (Three) page 0,0, and I started geeqie on monitor 1. When I started atril on second monitor, it was showed as it is on desk 0 (One).

On RootWinShot.20200916.182824.png I was with pager on desk 3 (Four) and left monitor and called gwenview. It appeared on screen, but FvwmPagers shows it on desk 2 (Three).

Screenshot RootWinShot.20200916.183209.png shows filezilla called on desk 3 (Four), but it appeared on desk 2 (Three) in FvwmPager.

Screenshot RootWinShot.20200916.184207.png is the most interesting. I turned off pager and called it again on second monitor and It appeared on screen without any windows in it. WindowList was called with middle click on root screen for comparation.

Screenshot RootWinShot.20200916.184315.png shows FvwmPager when called on left monitor immediately after that. It shows only one window - filezilla. WindowList is there for comparation.
![RootWinShot 20200916 182554](https://user-images.githubusercontent.com/48650374/93367794-4a3e7980-f84d-11ea-9031-b6daf23faf7b.png)
![RootWinShot 20200916 182824](https://user-images.githubusercontent.com/48650374/93367798-4b6fa680-f84d-11ea-95f9-946bf25df9de.png)
![RootWinShot 20200916 183209](https://user-images.githubusercontent.com/48650374/93367804-4d396a00-f84d-11ea-885a-8acf42aaf1e3.png)
![RootWinShot 20200916 184207](https://user-images.githubusercontent.com/48650374/93367809-4e6a9700-f84d-11ea-9595-425071351f80.png)
![RootWinShot 20200916 184315](https://user-images.githubusercontent.com/48650374/93367814-50345a80-f84d-11ea-8d10-f7abe3a862f1.png)

**Comment by ThomasAdam** [comment] 2020-09-27 19:20
Hi @NsCDE,

OK -- please take another look at the `ta/gh-223` branch.  You'll have to do this first of all:

```
git checkout ta/gh-223 ; git reset --hard @{u}
```

For the test cases that I've used, I can't get things to break -- but do let me know how you get on.

Thanks!

**Comment by NsCDE** [comment] 2020-09-28 06:30
Hi @ThomasAdam 

Please remind me what exactly to test here. After much debugging I must admint I'm bit lost. :-\

If we are talking about topis of this issue - DeskTopScale configuration of FvwmPager when configured with new "Monitor" option (either $$[pointer.screen] or explicit RandR name), than I must say that it still is taking into account joined monitors while calculating DeskTopScale.

If the topic is inconsistent window placement in global mode, where global and per-monitor are mixing, this is also the same. Active desk changes on screen where pointer is currently present, while window positions in FvwmPager are actually correct and FvwmIdent also confirms this as we discovered last time. Should I open separate topic for this, not to mix things with this issue?

**Comment by ThomasAdam** [comment] 2020-09-28 07:10
Hi @NsCDE

Thanks. Feel free to open a separate topic for the positioning of windows when in global mode.

With the recent changes to `ta/gh-223` I haven't been able to make windows move between desks or pages.

As for DesktopScale - I'll have to double check.

**Comment by NsCDE** [comment] 2020-09-28 11:26
Hi,

FYI, I found some time now to test a bit ... and here are my observations:

I can't find apps jumping in FvwmPager except sticky windows of course. It was hard to distinguish which was fvwm3 itself misbehaviour regarding #236 and what was FvwmPager itself, but now it looks like FvwmPager (and FvwmIdent) is more accurate than fvwm3. :-)

The subject of this issue looks like is still present - scaled aspect ratio of single monitor is of both monitors.

**Comment by ThomasAdam** [comment] 2020-09-28 11:50
Hi @NsCDE,

Hehehe -- thank you.  I've split out the code between this issue and 236, so that this issue is just concentrating on the DesktopScale problem, and 236 is focusing on the "jumping windows".

**Comment by NsCDE** [comment] 2020-10-03 19:10
Hi @ThomasAdam 

Today's new findings about this:

1. This is the configuration https://github.com/NsCDE/NsCDE/blob/fvwm3_support/NsCDE/config/NsCDE-Pager-GlobalPager.conf

2. Description:

* Configuration where I have direct `*GlobalPager: Monitor $$[monitor.current]` without prefixed condition `Test (EnvMatch FVWM_IS_FVWM3 1)` works in a way that I have one 4:3 Pager on primary screen and this same pager appears as 8:3 is called when pointer is on second screen, and empty (as it should be, because only window is on primary monitor), or has windows which are on secondary screen. Pager geometry should be 4:3 on both monitors.

* Configuration where I have `Test (EnvMatch FVWM_IS_FVWM3 1) *GlobalPager: Monitor $$[monitor.current]` behaves like this: it is 4:3 DeskTopScale on **both** monitors, but it shows the contents only of the first (primary) monitor, even if called when pointer is on secondary/right monitor.

* Configuration where "Monitor" FvwmPager directive is complitely removed behaves to show windows from all monitors on pages and desks, but pager is 4:3 if called on primary, and 8:3 if called on secondary monitor. In this case, it should probably be as on secondary monitor.

**Comment by ThomasAdam** [comment] 2020-12-07 00:05
Hi @NsCDE,

I'm trying to debug this issue.  I know a lot of things have perhaps changed since you raised it last.

If you have any time, would you mind testing against the latest `master` commit?  I would also love to know -- given the same configuration, whether you see the same thing with `fvwm2` as well -- albeit, the `*FvwmPager: Monitor $$[monitor.current]` won't mean anything to `Fvwm2`.

**Comment by NsCDE** [comment] 2020-12-08 19:40
Hi Thomas,

As you said, a lot of things have changed. This bug still persists and we even have regression here, because line `Test (EnvMatch FVWM_IS_FVWM3 1) *GlobalPager: Monitor $$[monitor.current]` does not work, while direct line `*GlobalPager: Monitor $$[monitor.current]` works, but works in a way that shows the right monitor depending the monitor context where pointer is, but on the second, non-primary monitor, dimensions of the pager are common joined, while on primary they are from just one monitor. Resolution on both virtual monitors is 1400x1050.

**Comment by ThomasAdam** [comment] 2021-06-11 16:29
Hi @NsCDE 

This should be fixed on the `js/pager-window-size`.  I know you're busy, but I'm leaving this here in case you or others find time to test it.  It's working well for me, so far...

**Closed** 2021-06-12 20:29 UTC
Labels: type:bug

**Comment by NsCDE** [comment] 2021-06-13 10:58
> Hi @NsCDE
> 
> This should be fixed on the `js/pager-window-size`. I know you're busy, but I'm leaving this here in case you or others find time to test it. It's working well for me, so far...

Hi @ThomasAdam 

Sorry for a delay. I have compiled current master where you merged this and tested this in global and per-monitor mode. It seems to be fixed for good. Didn't have a time to play with new "shared" mode ... see you more often on autumn hopefully.
