### ISSUE TITLE
conky can make fvwm3 go sloppy

### ISSUE THREAD

**Issue by MasterP-theGu** [fvwmorg/fvwm3#32] opened 2020-02-26 12:45 UTC
I usually put my conky onto the root window. In fvwm3 (desktops branch), the whole mouse-keyboard systems becomes very sloppy and slow as if it all happened inside a viscuous fluid. 

Running conky with "own_window yes" resolves the problem, running it without the "own_window" config makes the problem.

I cannot see any differences in CPU or RAM use between the two config scenarios.
My fvwm backround is set via the default fvwm config file (I like the flowers).

**Comment by ThomasAdam** [comment] 2020-03-02 23:41
Hi Peter,

I cannot reproduce this, I'm afraid.  Can you attach your `.conkyrc` file?  For me, there's no sluggishness,

**Comment by MasterP-theGu** [comment] 2020-03-03 15:59
Hi Thomas,
here's my conky.conf:

`conky.config = {
    alignment = 'top_right',
    background = true,
    border_width = 1,
    cpu_avg_samples = 2,
    default_color = 'white',
    default_outline_color = 'white',
    default_shade_color = 'white',
    double_buffer = true,
    draw_borders = false,
    draw_graph_borders = true,
    draw_outline = false,
    draw_shades = false,
    extra_newline = false,
    font = 'DejaVu Sans Mono:size=9',
    gap_x = -1200,
    gap_y = 60,
    minimum_height = 5,
    minimum_width = 5,
    maximum_width = 1000,
    net_avg_samples = 2,
    no_buffers = true,
    out_to_console = false,
    out_to_ncurses = false,
    out_to_stderr = false,
    out_to_x = true,
    own_window = true,
    own_window_class = 'Conky',
    own_window_type = 'desktop',
    own_window_hints = undecorated,below,sticky,skip_taskbar_skip_pager,
    own_window_transparent = true,
    show_graph_range = false,
    show_graph_scale = false,
    stippled_borders = 0,
    update_interval = 1.0,
    uppercase = false,
    use_spacer = 'none',
    use_xft = true,
    imap = " xxxxx ",
}
conky.text = [[
${color grey}$color $time
$hr
${color grey}Uptime:$color $uptime
${color grey}Frequency (in GHz):$color $freq_g
${color grey}RAM Usage:$color $mem/$memmax - $memperc% ${membar 4}
${color grey}CPU Usage:$color $cpu% ${cpubar 4}
${color grey}Processes:$color $processes  ${color grey}Running:$color           $running_processes
${color grey}Temperatur:$color $acpitemp °C
${color white}${hr 2}
${color white}Pinas
${execi 60 sshpass -f /home/peter/.ssh/xxx ssh peter@192.168.xx.xx uptime}
${execi 60 sshpass -f /home/peter/.ssh/xxx ssh peter@192.168.xx.xx /opt/vc/bin/vcgencmd measure_temp}
${color white}Pugserver
${execi 60 sshpass -f /home/peter/.ssh/xxx ssh  peter@192.168.78.42 uptime}
${color white}${hr 2}
${color grey}File systems:
 / $color${fs_used /}/${fs_size /} ${fs_bar 6 /}
${color grey}Networking:
ETH:  Up:$color ${upspeed eth0} ${color grey} - Down:$color ${downspeed eth0}
TUN:  Up:$color ${upspeed tun0} ${color grey} - Down:$color ${downspeed tun0}
WLAN: Up:$color ${upspeed wlan0} ${color grey} - Down:$color ${downspeed wlan0}
$hr
${color grey}Name              PID   CPU%   MEM%
${color lightgrey} ${top name 1} ${top pid 1} ${top cpu 1} ${top mem 1}
${color lightgrey} ${top name 2} ${top pid 2} ${top cpu 2} ${top mem 2}
${color lightgrey} ${top name 3} ${top pid 3} ${top cpu 3} ${top mem 3}
${color lightgrey} ${top name 4} ${top pid 4} ${top cpu 4} ${top mem 4}
${color #888888} ${top name 5} ${top pid 5} ${top cpu 5} ${top mem 5}

${color white}dmesg:
${exec dmesg  --notime | tail -n10}

${color #ddaa00}Tagesschau
${color white}${rss http://www.tagesschau.de/xml/rss2 1 item_titles 5}

${color #ddaa00}BBC
${color white}${rss http://newsrss.bbc.co.uk/rss/newsonline_uk_edition/front_page/rss.xml 1 item_titles 5}

${color orange} XXX ${execi 900 w3m -dump http://xxx | grep Stand}

Stundenplan - Inbox: ${imap_unseen}/${imap_messages}
]]
`
I hope you can make out the culprit.

**Comment by ThomasAdam** [comment] 2020-03-04 12:25
Hi Peter,

Still no luck, I'm afraid.  I'm wondering if it's your display driver?  I really can't see how this can be a FVWM problem, to be honest.  Are you using a style of `ParentialRelativity`?

**Comment by MasterP-theGu** [comment] 2020-03-06 20:18
Thomas,

I guess you're right about the display driver. It's one of the parameters that had changed with respect to my previous setup for fvwm2 and a single screen.
I had used the classic vc4 driver that I knew from my RPI3, but had to switch to V3D for RPI4. And it seems to be the V3D one that's causing the instability. With only conky running, everything seems fine, but the more windows I open, the laggier the mouse gets.
What seems to help a bit is to increase the framebuffer_depth to 32, but that doesn't solve the issue either.

So, this issue can probably be safely closed.

**Comment by ThomasAdam** [comment] 2020-03-06 20:19
Peter,

Yep, that makes complete sense.  Let's close this issue for now!

**Closed by ThomasAdam** 2020-03-06 20:19 UTC
Labels: enhancement, help wanted
