### ISSUE TITLE
Windows open outside of screen

### ISSUE THREAD

**Issue by afhp-2020** [fvwmorg/fvwm3#85] opened 2020-05-22 13:39 UTC
Another regression, may or may not be related to #68 ?

As of recently, and without apparent pattern, some windows will start opening outside the display. They didn't before, ~and once they start they always do.~

Currently observed with one specific contact window in Pidgin, and just now with Emacs.

xsession-error log:
```
[fvwm][GetWindowSizeHints]: <<WARNING>> reason: 6: The hints have been ignored because the window's current size would have become invalid.  The new hints will become active when the window generates the next ConfigureRequest.

[fvwm][GetWindowSizeHints]: <<WARNING>> The application window (id 0x720001c)
  "emacs@thorium" has broken size hints (inconsistent with current size).
    fvwm is ignoring those hints.    hint override = 0, flags = 350
  min_width = 40, min_height = 42, max_width = 40, max_height = 42
  width_inc = 8, height_inc = 16
  min_aspect = 0/0, max_aspect = 0/0
  base_width = 40, base_height = 42
  win_gravity = 1

    If you are having a problem with the application, send a bug report
    with this message included to the application owner.
    There is no need to notify fvwm-workers@fvwm.org.
[fvwm][GetWindowSizeHints]: <<WARNING>> reason: 6: The hints have been ignored because the window's current size would have become invalid.  The new hints will become active when the window generates the next ConfigureRequest.

[fvwm][GetWindowSizeHints]: <<WARNING>> The application window (id 0x720001c)
  "emacs@thorium" has broken size hints (inconsistent with current size).
    fvwm is ignoring those hints.    hint override = 0, flags = 350
  min_width = 40, min_height = 82, max_width = 40, max_height = 82
  width_inc = 8, height_inc = 16
  min_aspect = 0/0, max_aspect = 0/0
  base_width = 40, base_height = 82
  win_gravity = 1

    If you are having a problem with the application, send a bug report
    with this message included to the application owner.
    There is no need to notify fvwm-workers@fvwm.org.
Monitor Debug
	number of outputs: 2
	Name:	DVI-I-1
	Disabled:	false
	Is Primary:	yes
	Is Current:	no
	Output:	71
	Coords:	{x: 0, y: 240, w: 1920, h: 1200}
	VirtScr: {
		VxMax: 0, VyMax: 0, Vx: 0, Vy: 0
		EdgeScrollX: 0, EdgeScrollY: 0
		CurrentDesk: 1
		CurrentPage: {x: 0, y: 0}
		MyDisplayWidth: 2820, MyDisplayHeight: 1440
	}
	Desktops:	yes
	Flags:global

ewmh_ComputeAndSetWorkArea: monitor 'DP-2': {l: 0, r: 0, t: 0, b: 0} {x: 0, y: 0, w: 900, h: 1440}
ewmh_ComputeAndSetWorkArea: differ, so setting work area
ewmh_ComputeAndSetWorkArea: monitor 'DP-2': {l: 0, r: 0, t: 0, b: 0} {x: 0, y: 0, w: 900, h: 1440}
ewmh_ComputeAndSetWorkArea: monitor 'DP-2': {l: 0, r: 0, t: 0, b: 0} {x: 0, y: 0, w: 900, h: 1440}
ewmh_ComputeAndSetWorkArea: monitor 'DP-2': {l: 0, r: 0, t: 0, b: 0} {x: 0, y: 0, w: 900, h: 1440}
ewmh_ComputeAndSetWorkArea: monitor 'DP-2': {l: 0, r: 0, t: 0, b: 0} {x: 0, y: 0, w: 900, h: 1440}
ewmh_ComputeAndSetWorkArea: monitor 'DP-2': {l: 0, r: 0, t: 0, b: 0} {x: 0, y: 0, w: 900, h: 1440}
```
The window does appear in the window list, and one can check that it did open, in FvwmConsole: `Next (Emacs) Echo $[w.x] $[w.y]` will log
```
[fvwm][Echo]: 2820 0
```
Primary screen is 1920 px wide, right screen (rotated) is 900 px wide, window is positioned just outside of the viewable area.

The window can be brought back from the FvwmConsole with e.g. `Next (Emacs) Move pointer`, but it's annoying.

~I haven't seen a pattern as to why it _starts_ happening, but I've been juggling WMs and graphics drivers configurations lately, that probably doesn'h help.~

**EDIT**:
It would seem that this only happens when opening a window with the pointer on the right-hand monitor. Windows are positioned normally when the pointer is on the primary.
The FvwmConsole `Move pointer` command will work including when the pointer is on the right-hand monitor.

Still, in the case of the Pidgin contacts: with Pidgin's contact list as well as the pointer on the right-hand monitor, the chat window for one contact will open normally (on the right-hand monitor) while the window for another (always the same) will open outside of the display area.

**Comment by ThomasAdam** [comment] 2020-05-22 15:11
Hi @afhp-2020,

Weird.  I cannot reproduce this either.

Can you maybe take a video capture of the problems you're seeing here, and with #68 just so I can see what's going on visually?  Presumably I'm missing a piece of setup from what you've described, but can't tell what that might be.

**Comment by afhp-2020** [comment] 2020-05-22 20:28
I can't reproduce #68 (and it was at best just a guess), let's forget it.

Just to be sure, I wiped the fvwm3 build directory completely and re-cloned it (a few minutes ago), and rebuilt as described in your message.
`./configure` summary:
```
Fvwm Configuration:

  Version:     6927682c

  Executables: /usr/local/bin
  Man pages:   /usr/local/share/man
  Modules:     /usr/local/libexec/fvwm3/6927682c
  Data files:  ${prefix}/share/fvwm3
  Doc files:   ${prefix}/share/doc/fvwm3
  Perl lib:    ${prefix}/share/fvwm3/perllib
  Locale msg:  ${prefix}/share/locale  ar da de fr sv_SE zh_CN ru es

  With Asian bi-direct. text support? yes
  With Gettext Native Lang support?   yes (intl library)
  With Iconv support?                 yes (from C library)
  With Mouse strokes (gestures)?      no: Can't find working libstroke
  With ReadLine sup. in FvwmConsole?  yes
  With RPlay support in FvwmEvent?    no: Can't find working librplay
  With Shaped window support?         yes
  With Shared memory for XImage?      yes
  With Session Management support?    yes
  With SVG image support?             yes
  With Xcursor support?               yes
  With XRandR support?                yes
  With Xft anti-alias font support?   yes (version 2)
  With XPM image support?             yes
  With Xrender image support?         yes
  Build man pages?                    yes
  Build HTML documentation?           no
```
`fvwm3 --version`:
```$ fvwm3 --version
fvwm 6927682c compiled on May 22 2020 at 21:13:32
with support for: ReadLine, XPM, PNG, SVG, Shape, XShm, SM, Bidi text, XRandR, XRender, XCursor, XFT, NLS
```
Any place where I could drop the screencap ?

**Comment by ThomasAdam** [comment] 2020-05-22 20:50
@afhp-2020,

You should be able to.zip it up and attach it here.  Failing that, email it to me:  thomas@fvwm.org

**Comment by afhp-2020** [comment] 2020-05-22 22:23
[fvwm3-screencap.zip](https://github.com/fvwmorg/fvwm3/files/4670631/fvwm3-screencap.zip)

**Comment by ThomasAdam** [comment] 2020-05-24 17:47
@afhp-2020,

Is there any chance these applications (emacs, pidgin, etc.) are starting iconfied?  What if you did:

```
All (Iconified) Iconify off
```

In place of `Next (Emacs) Move pointer`?

**Comment by afhp-2020** [comment] 2020-05-24 22:28
Started an Emacs on right screen, didn't show. 

As above, at FvwmConsole `Next (Emacs) Echo $[w.x] $[w.y]` gives `[fvwm][Echo]: 2820 0` in the logs. 

`All (CurrentDesk, Iconic) Iconify off` de-iconifies the only window that was known to be in that state, but not the new Emacs window. (An iconified window would report the strings $[w.x] and $[w.y] as-is in the logs instead of coordinates.)

Performing a relative move with `Next (Emacs) Move w-10p w0p` I can see the left border of the Emacs window appear on the right edge of the right screen.

**Comment by ThomasAdam** [comment] 2020-05-24 22:40
Hi @afhp-2020,

OK.  I'm having problems reproducing your problem, but that's a good thing since it means you're using something I'm not.

Can you shove the following at the top of your FVWM3 config file:

```
BugOpts DebugRandR On
BugOpts ExplainWindowPlacement On
```

... and then can you send me the logs of FVWM3 to STDERR?  I need everything, so if you wanted to make FVWM3 log to a separate file, that makes sense:

```
fvwm3 ... >~/.fvwm3.log 2>&1
```

Thanks,
Thomas

**Comment by afhp-2020** [comment] 2020-05-25 17:44
[fvwm3-master20200525.log.txt](https://github.com/fvwmorg/fvwm3/files/4678297/fvwm3-master20200525.log.txt)
[fvwm3-gh48.log.txt](https://github.com/fvwmorg/fvwm3/files/4678298/fvwm3-gh48.log.txt)

Of course I had to mis-name the logfile and only see it after upload...

Same scenario (more or less) with master and with ta/gh-84: 

* open a non-character-cell application, e.g. Xfe on the primary and maximize it. Overlaps right-hand screen on master, correct maximization on ta/gh-84.
* open pidgin (right-hand screen) and contact window (same screen) that shows the off-screen bug. Explicitly open Emacs on right-hand screen. Same result: out-of-view on master, correct positioning inside right-hand monitor on ta/gh-84.

Excellent work :)

**Comment by ThomasAdam** [comment] 2020-05-25 22:03
Thanks, @afhp-2020 -- I'll close this now.

**Closed by ThomasAdam** 2020-05-25 22:03 UTC
Labels: bug
