### ISSUE TITLE
Function variables such as $[monitor.current] are not expanded while reading FvwmPager module configuration

### ISSUE THREAD

**Issue by NsCDE** [fvwmorg/fvwm3#380] opened 2020-12-22 13:41 UTC
* Fvwm3 version: master tree

* Linux distribution: Fedora 31

* Platform Linux x86_64

## Expected Behaviour

On every RandR monitor, pager for it with windows of that monitor are shown.

## Actual Behaviour

When pager is called from the secondary monitor, desks/pages from the first monitor are shown. If configuration is dinamically reread while pointer is on the second monitor, FvwmPager will show windows from the second monitor even if it is started on the primary. Behaviour is like static RandR names are hardcoded in the configuration.

## Steps to Reproduce

FvwmCommand 'DestroyModuleConfig FvwmPager: *'
FvwmCommand '*FvwmPager: Monitor $$[monitor.current]'
FvwmCommand 'KillModule FvwmPager'
FvwmCommand 'FvwmPager 0 4'

* Does the problem also happen with Fvwm2?

N/A (RandR)

Include your configuration with this issue.

## Extra Information

There was a closed issue #267 couple of months ago when FvwmPager module directives were not read after the Test (EnvMatch ...) stataments, which was a side-finding from the long standing #223 issue.

**Comment by ThomasAdam** [comment] 2020-12-22 13:48
Hi @NsCDE 

There's got to be something else missing here, since I've just ran your `FvwmCommand` lines, and when I issue `FvwmCommand "FvwmPager"` on either monitor, `FvwmPager` is correctly showing windows for just that monitor.

**Comment by ThomasAdam** [comment] 2020-12-22 14:00
@NsCDE 

The screenshot attached shows `FvwmPager` with the `FvwmCommand`s you provided and it's correctly showing widnows from each monitor separately.

I wonder what I'm missing here?
![each_000](https://user-images.githubusercontent.com/101281/102896269-05cf0500-445e-11eb-97a2-b2c4e88cb6e4.png)

**Comment by NsCDE** [comment] 2020-12-22 15:13
Hi Thomas,

Indeed, I cannot reproduce this with my own lines now! :-(

I have examined shell history on that xterm and this were exact steps:
```
 1027  FvwmCommand 'DestroyModuleConfig FvwmPager: *'
 1028  FvwmCommand '*FvwmPager: Monitor $$[monitor.current]'
 1029  FvwmCommand 'KillModule FvwmPager'
 1030  FvwmCommand 'FvwmPager 0 4'
 1031  sleep 3 && FvwmCommand 'FvwmPager 0 4'
```
The last line was 3 seconds time to escape to another monitor. Maybe I have accidentaly crossed for a millisecond on the first one. I really don't know.

**But** I have found the way to reproduce it:
If you click on the root window and choose "Global Pager" you will see what I'm talking about (probably).
But: if you run this then:

`FvwmCommand '*GlobalPager: Monitor $$[monitor.current]'`
... it will start to show proper monitor.

`FvwmCommand 'Test (EnvMatch FVWM_IS_FVWM3 1) *GlobalPager: Monitor $$[monitor.current]'`
will not work. It will carve current monitor into configuration instead, just like from config file.

It looks like we have regression of the issue #267 here.

**Comment by NsCDE** [comment] 2020-12-22 15:22
P. S.

I have examined https://github.com/fvwmorg/fvwm3/commit/e3d358802970da4758b78a929f2ba6b24d265614 and all looks ok, that is, in the current master in fvwm/modconf.c this modifications appears to be present. Something else changed ... someware.

**Comment by ThomasAdam** [comment] 2020-12-22 15:29
Yeah, there's no regression with that commit.

It's probably a regression with string-handling.  Will investigate.

**Comment by ThomasAdam** [comment] 2020-12-22 16:29
Does:

```
*GlobalPager: Monitor $$$[monitor.current]
```

... work?  If so, it's because there's now one further level of expansion which wasn't present before -- this was to make function parsing simpler, and only applies to sending module strings (`*Foo: whatever`) via `Test (...)`.

**Comment by NsCDE** [comment] 2020-12-22 17:32
Works with $$$ - a spammer variable. :)

Are you planning to leave it like that or treat as bug? I'm asking because if you plan to leave it like that, I should change permanently. :)

**Comment by ThomasAdam** [comment] 2020-12-22 21:50
@NsCDE 

Yep -- it has to be that way due to the number of indirect expansions which happen.  Please change your config accordingly.

I'll close this now.

**Closed by ThomasAdam** 2020-12-22 21:50 UTC
Labels: has:config, skip:changelog, type:bug
