### ISSUE TITLE
FvwmPager does not notice virtual desktop size changes

### ISSUE THREAD

**Issue by galibert** [fvwmorg/fvwm3#954] opened 2024-02-23 08:18 UTC
Thanks for reporting your bug here!  The following template will help with
giving as much information as possible so that it's easier to diagnose and
fix.

## Upfront Information

Please provide the following information by running the command and providing
the output.

* Fvwm3 version (run: `fvwm3 --version`)

fvwm3 1.1.0 (1.0.9-15-g4af6dbe6)

* Linux distribution or BSD name/version

Archlinux

* Platform (run: `uname -sp`)

Linux unknown

## Expected Behaviour

When switching monitors on or off through xrandr/arandr, fvwm3 notices the changes and acts as needed (good job there!) but FvwmPager doesn't.  Specifically, the sizes of the individual desktops in a larger virtual desktop do not change.  A restart fixes things.

## Actual Behaviour

FvwmPager should change the size of the individual desktops and the global virtual desktop as needed.  Moving windows around when they end up fully outside of the virtual desktop, or when their geometry is relative to the borders, is left as an exercise to the reader.

* Does the problem also happen with Fvwm2?

fvwm2 ends up utterly confused when the monitor configuration changes.  fvwm3 is infinitely better in this regard.

**Comment by ThomasAdam** [comment] 2024-03-29 18:09
This should be fixed via #978

**Closed** 2024-03-29 21:37 UTC
Labels: type:bug, relates:module

**Comment by galibert** [comment] 2024-04-02 21:25
That didn't work out, or at least not entirely.

Here is my final monitor configuration: 
![monitors](https://github.com/fvwmorg/fvwm3/assets/9249521/8401e888-110d-414b-b1f3-2f023530dc84)

Starting from single-monitor (eDP-1), the pager looks like that: 
![pager-1a](https://github.com/fvwmorg/fvwm3/assets/9249521/596fd857-6db8-4ea2-a4be-715a8892c54f) which is correct (DeskTopSize 4x4).

After switching on the other two monitors, it ends up like that: 
![pager-2a](https://github.com/fvwmorg/fvwm3/assets/9249521/08af6fae-a9df-4354-a2d2-a818ebcd9c88) .  It also refuses mobing between virtual desktops at this point, thinking it's 1x1 I guess?

Then after reload things are back to normal: 
![pager-3a](https://github.com/fvwmorg/fvwm3/assets/9249521/2a726716-79de-4662-bb2b-94a9b639fb08)

**Comment by somiaj** [comment] 2024-04-02 21:36
Are you trying this with 1.1.0? I can't reproduce this. I start with a single monitor running, and I then enable my second monitor, and here the pager updates its sizes for both monitors and the page grid is still visible. I'm not quite sure what could be happening on your end.

**Comment by galibert** [comment] 2024-04-02 22:41
1.1.0-1-g5b82cba6

I'm not sure how I issue something when live?

**Comment by somiaj** [comment] 2024-04-02 22:50
You can use `FvwmPrompt`, `FvwmConsole`, or `FvwmCommand`.

**Comment by somiaj** [comment] 2024-04-02 22:57
I think what is happening is when you add new monitors, their info gets sent to the pager before their number of pages is setup, and thus the pager thinks you only have a desktop size of `1x1` which explains what you see and why it acts like there is only one page. Issuing the `DesktopSize` commands should refresh the pager's understanding (my theory) of how many pages there are, without having to restart fvwm. I still can't reproduce this, so unsure what is triggering the pager thinking your desktop size is only `1x1`.

**Comment by galibert** [comment] 2024-04-02 22:58
FvwmCommand 'DesktopSize 4x4' resets the pager to normal.  So yeah, the size is lost somewhere.

**Comment by galibert** [comment] 2024-04-02 22:59
My .fvwm2rc just in case.
[fvwm2rc.txt](https://github.com/fvwmorg/fvwm3/files/14844515/fvwm2rc.txt)

**Comment by somiaj** [comment] 2024-04-02 23:02
Well you now have a temporary fix, there is a `RandRFunc` you can use to help you until we track down the issue in fvwm. Try this.

```
DestroyFunc RandRFunc
AddToFunc RandRFunc I DesktopSize 4x4
```

that should send a desktopsize command with monitor changes, maybe it can help your issue.

**Comment by galibert** [comment] 2024-04-02 23:07
Something maybe unusual about my layout is that when I active the otehr two monitors, eDP-1 is not top left nor primary anymore.  Dunno if your testing is similar.

**Comment by somiaj** [comment] 2024-04-02 23:18
I don't think it is your layout, I think it is something else, maybe a race condition. I did try activating a monitor to the left instead of to the right. Anyways, we have enough info for now as to what might be the cause, hopefully the `RandRFunc` can at least make things work better for you until we track the issue down.
